config/routes.rb
Rails.application.routes.draw do
  
  unauthenticated do
    root :to => 'welcome#index'

  end
 
  authenticated do
    root :to => 'welcome#log_in_welcome'
  end
  
  get '/plants/in_garden', to: 'plants#in_garden'
  get '/plants/edible', to: 'plants#edible'
  get '/plants/annual', to: 'plants#annual'

  resources :plants do
    resources :actions, only: :index
    resources :plants_actions, only: [:new, :create]
  end

  resources :actions, only: [:index, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :users, only: :index do
    resources :plants, only: :index 
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def log_in_welcome
    @plants = Plant.all
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper

  def number_of_plants
    @plants.select{|plant| plant.user_id == current_user.id}.count
  end
end

app/views/welcome/index.html.erb
<h2>Welcome to Plantalog!</h2><br><br>
<p>Let's get started!</p>

app/views/welcome/log_in_welcome.html.erb
<h2>Welcome to Plantalog!</h2><br>
<div class="logged-in">
<% if !current_user.admin %>
  <% if number_of_plants > 0 %>
    <h3>You have <b><%= number_of_plants %></b> plants in your log.</h3><br><br>
    <p><%#= link_to "View all the plants", plants_path %></p>
    <button id='show-button'>Show Plants</button>
    <div id='show-plants'></div>
    <br><br>
  <% else %>
    <h4>Looks like you don't have any plants in your log.</h4>
    <h4>Let's get started by entering some plants in your log!</h4>
  <% end %><br><br>

  <%= link_to "Enter new plant", new_plant_path, :class => "new-plant"%><br><br>
  <%# I want to use button_to but it shows ? at the end of url. figure out how to fix it then change to button_to. %>
  <%#= button_to "Enter new plant", new_plant_path, :class => "new-plant", :method => :get %><br><br>

<% end  %>
<br><br>

<% if current_user.admin %>
  <h4><b><%= current_user.username.capitalize %></b>, you are logged in as an admin.</h4><br>
  <p>You can 
  <ul>
  <li><%= link_to "View all users", users_path %></li>
  <li><%= link_to "View all actions", actions_path %></li>
  </ul></p>
    
<% end  %>