config/routes.rb
Rails.application.routes.draw do
  
  unauthenticated do
    root :to => 'welcome#index'

  end
 
  authenticated do
    root :to => 'welcome#log_in_welcome'
  end
  
  get '/plants/in_garden', to: 'plants#in_garden'
  get '/plants/edible', to: 'plants#edible'
  get '/plants/annual', to: 'plants#annual'

  resources :plants do
    resources :actions, only: :index
    resources :plants_actions, only: [:new, :create]
  end

  resources :actions, only: [:index, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :users, only: :index do
    resources :plants, only: :index 
  end

end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :user
  has_many :plants_actions
  has_many :actions, through: :plants_actions
  accepts_nested_attributes_for :plants_actions, :allow_destroy => true
  accepts_nested_attributes_for :actions, :allow_destroy => true

  validates_presence_of :name, :message => "for plant can't be blank."
    
  def plants_actions_attributes=(plant_action_attribute)
    plant_action_attribute.values.each do |plant_action_hash|
    if plant_action_hash[:action_date].present?
      pa = PlantsAction.find_or_create_by(plant_id: self.id, action_id: plant_action_hash[:action_id])
      pa.update(action_date: plant_action_hash[:action_date])
      self.plants_actions << pa unless self.id
      end
    end
  end
  
  def actions_attributes=(action_attribute)
    if action_attribute["0"][:action_name].present? 
      action = Action.create(action_name: action_attribute["0"][:action_name])
      pa = PlantsAction.new(action_date: action_attribute["0"][:plants_actions_attributes]["0"][:action_date],
                            action_id: action.id) 
      self.plants_actions << pa
    end
  end

  def self.in_garden_msd(user)
    where(in_the_garden: true, user_id: user.id)
  end

  def self.edible_msg(user)
    where(edible: true, user_id: user.id)
  end

  def self.annual_msg(user)
    where(annual: true, user_id: user.id)
  end

end

app/models/plantaction.rb
class Plantaction < ApplicationRecord
  belongs_to :plants
  belongs_to :actions
end

app/models/plants_action.rb
class PlantsAction < ApplicationRecord
  belongs_to :plant, optional: true
  belongs_to :action, optional: true
  accepts_nested_attributes_for :action, :allow_destroy => true
  validates_presence_of :action, :scope => :action_id, :message => "must have a checkbox checked first, before selecting a date"
  validates_presence_of :action_date

  def action_attributes=(action_hash)
    action = Action.create(action_hash)
    self.action = action
  end
end
 

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_plant, only: [:show, :edit, :update]
  
  def index
    if current_user.admin
      owner_id = params[:user_id].to_i  
      @plants_owner = User.find(owner_id)
      @plants = Plant.where(user_id: owner_id) 
    else
      @plants = current_user.plants
    end
    respond_to do |f|
      f.html
      f.json {render json: @plants}
    end
  end

  def new
    @plant = Plant.new
    Action.all.each do |action|
      @plant.plants_actions.build(action_id: action.id)
    end
  end

  def create
    @plant = current_user.plants.new(plant_params)
    if @plant.save
      # redirect_to plant_path(@plant)
      render json: @plant, status: 201
    else
        flash[:danger] =  @plant.errors.full_messages.to_sentence
      redirect_to new_plant_path
      #render new and restyle flash
    end
  end

  def show
    respond_to do |f|
      f.html
      f.json {render json: @plant}
    end
  end

  def edit
    @user = current_user
  end

  def update
    @plant.update(plant_params) 
    redirect_to plant_path(@plant)
  end

  def destroy
    Plant.find(params[:id]).destroy
    redirect_to plants_path
  end

  def in_garden
    @plants  = Plant.in_garden_msd(current_user)
  end

  def edible
    @plants  = Plant.edible_msg(current_user)
  end

  def annual
    @plants = Plant.annual_msg(current_user)
  end

  private 

  def plant_params
    params.require(:plant).permit(:name, :in_the_garden, :edible, :annual, :user_id, :note,
      :plants_actions_attributes => [:action_id, :action_date],
      :actions_attributes => [:action_name,
        :plants_actions_attributes => :action_date])
  end

  def set_plant
    @plant = Plant.find_by(id: params[:id])
  end
end

app/helpers/plants_helper.rb
module PlantsHelper

  def in_the_garden?
    if @plant.in_the_garden == true
      "Yes"
    else
      "No"
    end
  end

  def edible?
    if @plant.edible == true
      "Yes"
    else
      "No"
    end
  end

  def annual?
    if @plant.annual == true
      "Yes"
    else
      "No"
    end
  end

  def memo
    if @plant.note.present?
      "Memo: #{@plant.note}"
    end
  end

  def find_action_name(pa)
    id = pa.object.action
    Action.find(id).action_name 
  end 

end

app/views/plants/_booleans.html.erb
<ul><% @plants = @plants.sort {|a,b|a.name <=> b.name} %>
<% @plants.each do |plant| %>
<li><h4><%= plant.name %></h4></li>
<% end %></ul>

<br><br>
<%= link_to "View all the plants", plants_path %>

app/views/plants/_form.html.erb
<% if flash[:danger] %>
    <div class='alert alert-danger'><%= flash[:danger] %></div>
<% end %>
<div class="form-container">
  <%= form_for @plant, :html => {:id => "new_plant"} do |f| %>

    Name: <%= f.text_field :name %><br><br>
    Is it planted in your garden now?  <%= f.check_box :in_the_garden%><br><br>
    Is it edible?  <%= f.check_box :edible %><br><br>
    Is it an annual plant?  <%= f.check_box :annual %><br><br>
    Memo: <%= f.text_field :note %><br><br>

    <br><br>
    <h4>What actions do you need to take for the plant? When do they happen?</h4>
    <p>Please select actions need to be taken and set dates or create a new action</p>
    <br><br>
    
    <%= f.fields_for :plants_actions, @plant.plants_actions do |pa| %>
    <ul>
      <% if edit == true %>
      <li><%= pa.label pa.object.action.action_name %> <%= pa.hidden_field :action_id, :value => pa.object.action_id %><br>
              <%= pa.label "Change the date" %>  <%= pa.date_field :action_date %></li>
      <% else %>
          <li><%= pa.label pa.object.action.action_name %>  <%= pa.check_box :action_id, {checked: false}, pa.object.action_id, "" %></li>
              <%= pa.label "select a date" %> <%= pa.date_field :action_date %></li>
      <% end %>
    </ul>
    <% end  %>


      <br><br>
      Add more action : 
          
      <%= f.fields_for :actions, @plant.plants_actions.build.build_action do |a| %>
        <%= a.label :action_name %> <%= a.text_field :action_name %><br>
        
        <%= a.fields_for :plants_actions, @plant.plants_actions.build do |apa| %>
        <%= apa.label "select a date"  %> <%= apa.date_field :action_date %>
        <% end  %>
        <br>
      <% end  %>
      
    <br><br>
  <%= f.submit %>
  <% end %>
  <br><br>
</div>
<%= link_to "View all the plants", plants_path %>

app/views/plants/annual.html.erb
<h3>Plants that are annual</h3><br><br>
<% if @plants.count == 0 %>
  <div class='alert alert-info'><%= flash[:info] = "You don't have any annual plant yet."%></div>
<% end %>
<%= render 'booleans' %>

app/views/plants/edible.html.erb
<h3>Plants that are edible</h3><br><br>
<% if @plants.count == 0 %>
  <div class='alert alert-info'><%= flash[:info] = "You don't have any edible plant yet."%></div>
<% end %>
<%= render 'booleans' %>

app/views/plants/edit.html.erb
<h3>Edit</h3>
<%= render :partial => 'form', :locals => {edit: true} %>

app/views/plants/in_garden.html.erb
<h3>Plants that are in your garden</h3><br><br>
<% if @plants.count == 0 %>
  <div class='alert alert-info'><%= flash[:info] = "You don't have anything planted in your garden yet."%></div>
<% end %>
<%= render 'booleans' %>

app/views/plants/index.html.erb
<% if current_user.admin %>
  <h4><%= @plants_owner.email.split('@')[0].capitalize %> has <%= @plants_owner.plants.count %> plants</h4>
  <ul><% @plants.each do |plant| %>
    <li><%=  plant.name%></li>
  <% end %></ul>
 <% else %>
 <br>
  <h4>You have <%= current_user.plants.count %> plants</h4><br>
  <ul><% @plants.each do |plant| %>
    <li><%= link_to plant.name.capitalize, plant_path(plant) %></li>
  <% end %></ul><br><br>

  <%= link_to "Log more plants", new_plant_path %><br><br><br>
  <%= link_to "View all the plants in the garden", plants_in_garden_path %><br><br>
  <%= link_to "View edible plants", plants_edible_path %><br><br>
  <%= link_to "View annual plants", plants_annual_path %><br><br>
<% end %><br>


<%= link_to "Go Back", users_path %>

app/views/plants/new.html.erb
<h3>Let's enter plant data!</h3>
<br><br>
<%= render :partial => 'form', :locals => {edit: false} %>

app/views/plants/show.html.erb
<h3><%= @plant.name.capitalize %></h3><br>
<h4>Is it planted in your garden? <%= in_the_garden? %></h4><br>
<h4>Is it edible? <%= edible? %></h4><br>
<h4>Is it an annual plant? <%= annual? %></h4><br>
<h4><%= memo %></h4><br>

<h4>Actions</h4>
<% if @plant.actions.count > 0 %>
  <ul>
  <% @plant.plants_actions.each do |pa| %>
      <li><%= pa.action.action_name.capitalize %>  Date: <%= pa.action_date %></li>
    <% end %>
  </ul>
<% end %>
<%=  link_to "Create another action", new_plant_plants_action_path(@plant) %><br><br>
<%# The link above is made to meet the requirement. 
May delete after the assesment since a user can create new action in edit page %>
<br><br>
<%=  link_to "See all the plants", plants_path%><br><br>
<%=  link_to "Edit this plant", edit_plant_path %><br><br>
<%=  link_to "Delete this plant", @plant, method: :delete, data: { confirm: "Really?" } %>