config/routes.rb
Rails.application.routes.draw do
  
  unauthenticated do
    root :to => 'welcome#index'

  end
 
  authenticated do
    root :to => 'welcome#log_in_welcome'
  end
  
  get '/plants/in_garden', to: 'plants#in_garden'
  get '/plants/edible', to: 'plants#edible'
  get '/plants/annual', to: 'plants#annual'

  resources :plants do
    resources :actions, only: :index
    resources :plants_actions, only: [:new, :create]
  end

  resources :actions, only: [:index, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :users, only: :index do
    resources :plants, only: :index 
  end

end

app/controllers/plants_actions_controller.rb
class PlantsActionsController < ApplicationController
  before_action :authenticate_user!
    
  def new
    @plant = Plant.find_by(id: params[:plant_id]) 
    @plant_action = @plant.plants_actions.build
  end

  def create
    @plant = Plant.find_by(id: params[:plant_id]) 
    @plant_action = @plant.plants_actions.build(plants_action_params)
    if @plant_action.save
      redirect_to plant_path(@plant)
    else
      flash[:danger] = "Both fields need filled and a name has to be unique."
      redirect_to new_plant_plants_action_path
    end
  end

  private

  def plants_action_params
    params.require(:plants_action).permit(:action_date, 
      :action_attributes => [:action_name])
  end
end

app/helpers/plants_actions_helper.rb
module PlantsActionsHelper
 
end

app/views/plants_actions/new.html.erb
<% if flash[:danger] %>
    <div class='alert alert-danger'><%= flash[:danger] %></div>
<% end %>
<h4>Creating an action for <b><%= @plant.name%></b></h4>
<br>
<%= form_for @plant_action, url: plant_plants_actions_path do |f| %>

  <%= f.fields_for :action, @plant_action.build_action do |a| %>
    <%= a.label :action_name %><%= a.text_field :action_name%><br>
  <% end %>
<%= f.label "select a date"  %> <%= f.date_field :action_date %><br><br>
<%= f.submit "Create an action"%>
<% end %>
<br><br>
<%= link_to "Go back", plant_path(@plant) %>